### ISSUE TITLE
got a 128 status code when execute "git commit ..."

### ISSUE THREAD

**Issue by baizhiqiang** [kalyabin/yii2-git-view#1]
I got a `Command git --no-pager commit -m 'commit10' ended with 128 status code` exception when I execute a commit command,but it works well when I execute a 'add' command.
What's the problem?
system:win7 64bit

**Comment by kalyabin** [comment]
`git commit` does not supports `--no-pager` option. But this extension uses this option by default, because it deactivates interactive mode for git command.

This extension is useful only for view references, but not for create. I recommend you to use native commands to create new commits.

**Comment by baizhiqiang** [comment]
Thanks anyway .
I'm trying to write a novel version control system for the writers ,Would you tell me how the web site like github stores files ,in DB or just in hard disk on server?
sorry for my English.

**Comment by kalyabin** [comment]
I think that github stores files in hard disk, but contributions stored in DB.

You can see my project https://github.com/kalyabin/comitka 
I began to develop a similar project, but main feature for this is flexible code review system. You can start to contribute this system.

**Comment by baizhiqiang** [comment]
Thanks man .
